/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

/**
 *
 * @author Usuario
 */
public class AgregarProductos extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    int numeroProdut;
    int acum=1;
    ProductTester product = ProductTester.getAdm();

    public AgregarProductos() {
        initComponents();
        setSize(507, 339);
        setLocationRelativeTo(null);
        setResizable(false);
        this.lbl_productos.setText("Producto #1");
    }

    public AgregarProductos(int numeroProductos){
        initComponents();
        setSize(507, 339);
        setLocationRelativeTo(null);
        setResizable(false);
        this.lbl_productos.setText("Producto #1");
        numeroProdut = numeroProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txt_numeroProducto = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        btn_minimizar = new javax.swing.JButton();
        lbl_productos = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNombre.setText("ID_PUESTO:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txt_nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, -1));

        lblCantidad.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCantidad.setText("Nombre del puesto:");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));

        lblPrecio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPrecio.setText("Salario Minimo");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));

        lblNumero.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNumero.setText("Salario Maximo");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txt_numeroProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_numeroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 120, 30));

        btn_guardar.setBackground(new java.awt.Color(51, 0, 153));
        btn_guardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 140, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 190, 140, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_40px.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_50px.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 0, 40, 40));

        btn_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_macos_minimize_40px.png"))); // NOI18N
        btn_minimizar.setBorder(null);
        btn_minimizar.setBorderPainted(false);
        btn_minimizar.setContentAreaFilled(false);
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_macos_minimize_50px.png"))); // NOI18N
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 0, 40, 40));

        lbl_productos.setBackground(new java.awt.Color(255, 255, 255));
        lbl_productos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_productos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_productos.setText("Puesto");
        jPanel1.add(lbl_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HD-wallpaper-blur-gradation-soft-pastel-red.jpg"))); // NOI18N
        lbl_fondo.setText("Salario maximo");
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int xx = evt.getXOnScreen();
        int xy = evt.getYOnScreen();

        this.setLocation(xx - x, xy - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    int x, y;
    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String nombre = txt_nombreProducto.getText().trim();
        int cantidad = Integer.parseInt(txt_cantidad.getText().trim());
        double precio = Double.parseDouble(txt_precio.getText().trim());
        int numeroElem = Integer.parseInt(txt_numeroProducto.getText().trim());

        product.guardarProducto(nombre, cantidad, precio, numeroElem);

        if (acum == numeroProdut) {
            IngresarSistema sistema = new IngresarSistema();
            sistema.setVisible(true);
            this.setVisible(false);
        }

        acum++;
        this.lbl_productos.setText("Producto #" + acum);
        Limpiar();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_productos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_nombreProducto;
    private javax.swing.JTextField txt_numeroProducto;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txt_nombreProducto.setText("");
        txt_numeroProducto.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");

        txt_nombreProducto.requestFocus();
    }
}
