/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.puestosForm;

import java.math.BigDecimal;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

import common.Comboitem;
import model.Departamento;
import model.Puesto;
import model.RiesgoPuesto;
import service.DepartamentoService;
import service.PuestoService;
import service.RiesgoPuestoService;

/**
 *
 * @author Joel Grullon
 */
public class EditarPuestoForm extends javax.swing.JInternalFrame {

    private PuestoService puestoService;
    private RiesgoPuestoService riesgoService;
    private DepartamentoService depaService;
    private Puesto puestoEditado;
    private PuestosForm parent;

    private List<RiesgoPuesto> listaRiesgos;
    private List<Departamento> listaDepas;
 
    /**
     * Creates new form EditarPuestoForm
     */
    public EditarPuestoForm(Puesto puesto, PuestosForm puestoForm) {
        parent=puestoForm;
        puestoService=new PuestoService();
        riesgoService=new RiesgoPuestoService();
        depaService=new DepartamentoService();

        initComponents();

        cargarRiesgos();
        cargarDepartamentos();

        cargarPuesto(puesto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRiesgo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSalarioMaximo = new javax.swing.JSpinner();
        txtSalarioMinimo = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnEditar = new javax.swing.JButton();

        setTitle("Editar Puesto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Salario Maximo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 45, -1, -1));

        getContentPane().add(cmbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 250, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, -1));

        jLabel2.setText("Nombre Puesto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel3.setText("Departamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        getContentPane().add(cmbRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 200, -1));

        jLabel4.setText("Salario Minimo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel5.setText("Riesgo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 15, -1, -1));
        getContentPane().add(txtSalarioMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 200, -1));
        getContentPane().add(txtSalarioMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 200, -1));

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 590, 100));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarRiesgos(){
        listaRiesgos=riesgoService.getAll();

        cmbRiesgo.removeAllItems();

        for (RiesgoPuesto riesgoPuesto : listaRiesgos) {
            cmbRiesgo.addItem(new Comboitem(riesgoPuesto.getIdRiesgo(), riesgoPuesto.getNombreRiesgo()));
        }
    }

    private void cargarDepartamentos(){
        listaDepas=depaService.getAll();

        cmbDepartamento.removeAllItems();

        for (Departamento depa : listaDepas) {
            cmbDepartamento.addItem(new Comboitem(depa.getIdDepartamento(), depa.getNombreDepartamento()));
        }
    }

    private void cargarPuesto(Puesto puesto){
        puestoEditado=puesto;

        RiesgoPuesto riesgoSeleccionado=listaRiesgos.stream()
        .filter(x->x.getIdRiesgo()==puesto.getRiesgoId())
        .findFirst()
        .orElse(null);

        Departamento depaSeleccionado=listaDepas.stream()
        .filter(x->x.getIdDepartamento()==puesto.getDepartamentoId())
        .findFirst()
        .orElse(null);

        txtNombre.setText(puesto.getNombrePuesto());
        txtSalarioMinimo.setValue(puesto.getSalarioMinimo());
        txtSalarioMaximo.setValue(puesto.getSalarioMaximo());
        cmbRiesgo.setSelectedItem(new Comboitem(puesto.getRiesgoId(), riesgoSeleccionado.getNombreRiesgo()) );
        cmbDepartamento.setSelectedItem(new Comboitem(puesto.getDepartamentoId(), depaSeleccionado.getNombreDepartamento()));
        txtDesc.setText(puesto.getDescripcion());
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // JOptionPane.showMessageDialog(this, "Valores: "+txtSalarioMinimo.getValue()+", "+txtSalarioMaximo.getValue());
        // return;

        puestoEditado.setNombrePuesto(txtNombre.getText());
        puestoEditado.setRiesgoId(((Comboitem)cmbRiesgo.getSelectedItem()).getId());
        puestoEditado.setSalarioMinimo( new BigDecimal(txtSalarioMinimo.getValue().toString()));
        puestoEditado.setSalarioMaximo(new BigDecimal(txtSalarioMaximo.getValue().toString()));
        puestoEditado.setDepartamentoId(((Comboitem)cmbDepartamento.getSelectedItem()).getId());
        puestoEditado.setDescripcion(txtDesc.getText());

        if(!puestoService.update(puestoEditado)){
            JOptionPane.showMessageDialog(this, "Error al editar el puesto");
            return;
        }

        JOptionPane.showMessageDialog(this, "Puesto editado correctamente");
        parent.cargarPuestos();
        this.dispose();
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox<Comboitem> cmbDepartamento;
    private javax.swing.JComboBox<Comboitem> cmbRiesgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JSpinner txtSalarioMaximo;
    private javax.swing.JSpinner txtSalarioMinimo;
    // End of variables declaration//GEN-END:variables
}
