/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.puestosForm;

import java.math.BigDecimal;
import java.util.List;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import common.Comboitem;
import model.Departamento;
import model.Idioma;
import model.Puesto;
import model.RiesgoPuesto;
import service.DepartamentoService;
import service.PuestoService;
import service.RiesgoPuestoService;
import view.MainPage;
import view.idiomaForm.EditarIdiomaForm;

/**
 *
 * @author JoelGrullon
 */
public class PuestosForm extends javax.swing.JInternalFrame {

    private PuestoService puestoService;     
    private DefaultTableModel tblPuestosModel;
    private RiesgoPuestoService riesgoService;
    private DepartamentoService depaService;
    private JDesktopPane mainDesktop;
    private List<Puesto> listaPuestos;

    /**
     * Creates new form PuestosPage
     */
    public PuestosForm(JDesktopPane desktop) {
        mainDesktop=desktop;
        puestoService=new PuestoService();
        riesgoService=new RiesgoPuestoService();
        depaService=new DepartamentoService();

        initComponents();
        initTable();
        setupTableListener();
        cargarRiesgos();
        cargarDepartamentos();

        cargarPuestos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRiesgo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPuestos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtSalarioMinimo = new javax.swing.JSpinner(new SpinnerNumberModel(0.00, 0.00, 10000000.00, 1.00));
        txtSalarioMaximo = new javax.swing.JSpinner(new SpinnerNumberModel(0.00, 0.00, 10000000.00, 1.00));

        setClosable(true);
        setTitle("Gestionar Puestos");

        jLabel1.setText("Nombre Puesto");

        jLabel2.setText("Salario Minimo");

        jLabel3.setText("Riesgo");

        cmbRiesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRiesgoActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jLabel5.setText("Salario Maximo");
        jScrollPane2.setViewportView(tblPuestos);

        jLabel6.setText("Departamento");

        cmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSalarioMinimo)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRiesgo, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtSalarioMaximo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtSalarioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        String[] header = {"ID", "Nombre", "Salario Max.", "Salario Min.", "Riesgo", "Departamento"};
        tblPuestosModel = new DefaultTableModel(header, 0);
        tblPuestos.setModel(tblPuestosModel);
    }

    private void cargarRiesgos(){
        List<RiesgoPuesto> listaRiesgos=riesgoService.getAll();

        cmbRiesgo.removeAllItems();

        for (RiesgoPuesto riesgoPuesto : listaRiesgos) {
            cmbRiesgo.addItem(new Comboitem(riesgoPuesto.getIdRiesgo(), riesgoPuesto.getNombreRiesgo()));
        }
    }

    private void cargarDepartamentos(){
        List<Departamento> listaDepas=depaService.getAll();

        cmbDepartamento.removeAllItems();

        for (Departamento depa : listaDepas) {
            cmbDepartamento.addItem(new Comboitem(depa.getIdDepartamento(), depa.getNombreDepartamento()));
        }
    }

    private void setupTableListener() {
        // Configurar botones inicialmente deshabilitados
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);

        // Agregar listener una sola vez para habilitar/deshabilitar botones al seleccionar fila
        tblPuestos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { // Evitar múltiples eventos
                    boolean filaSeleccionada = tblPuestos.getSelectedRow() != -1;
                    btnEditar.setEnabled(filaSeleccionada);
                    btnEliminar.setEnabled(filaSeleccionada);
                }
            }
        });
    }

    public void cargarPuestos(){
        try {
            listaPuestos = puestoService.getAllWithRelationships();
            
            // Limpiar tabla
            tblPuestosModel.setRowCount(0);
            
            // Llenar tabla con datos
            for (Puesto puesto : listaPuestos) {
                tblPuestosModel.addRow(new Object[]{
                    puesto.getIdPuesto(),   
                    puesto.getNombrePuesto(),   
                    puesto.getSalarioMinimo(), 
                    puesto.getSalarioMaximo(), 
                    puesto.getRiesgo().getNombreRiesgo(),
                    puesto.getDepartamento().getNombreDepartamento()
                    //idi.getNivel() != null ? idi.getNivel() : ""
                });
            }
            
            // Limpiar selección
            tblPuestos.clearSelection();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar puestos: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void cmbRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRiesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRiesgoActionPerformed

    private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartamentoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Puesto nuevoPuesto=new Puesto();
        nuevoPuesto.setNombrePuesto(txtNombre.getText());
        nuevoPuesto.setRiesgoId(((Comboitem)cmbRiesgo.getSelectedItem()).getId());
        nuevoPuesto.setSalarioMinimo( new BigDecimal(txtSalarioMinimo.getValue().toString()));
        nuevoPuesto.setSalarioMaximo(new BigDecimal(txtSalarioMaximo.getValue().toString()));
        nuevoPuesto.setDepartamentoId(((Comboitem)cmbDepartamento.getSelectedItem()).getId());
        nuevoPuesto.setDescripcion(txtDesc.getText());

        if(!puestoService.insert(nuevoPuesto)){
            JOptionPane.showMessageDialog(this, "Error al insertar un nuevo puesto");
            return;
        }

        JOptionPane.showMessageDialog(this, "Puesto insertado correctamente");
        limpiarCampos();
        cargarPuestos();
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int filaSeleccionada = tblPuestos.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un idioma para editar.");
            return;
        }

        Puesto puestoSeleccionado = listaPuestos.get(filaSeleccionada);

        EditarPuestoForm editarIdiomaForm = new EditarPuestoForm(puestoSeleccionado, this);
        mainDesktop.add(editarIdiomaForm);
        editarIdiomaForm.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int option= JOptionPane.showConfirmDialog(this, "Estas seguro que desea eliminar este puesto?", "Eliminar puesto", JOptionPane.YES_NO_OPTION);

       if(option!=JOptionPane.YES_OPTION){
        return;
       }

       int filaSeleccionada = tblPuestos.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un idioma para eliminar.");
            return;
        }

        Puesto puestoSeleccionado = listaPuestos.get(filaSeleccionada);
        puestoService.delete(puestoSeleccionado.getIdPuesto());

            JOptionPane.showMessageDialog(this, "Puesto eliminado correctamente");
            cargarPuestos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void limpiarCampos(){
        txtNombre.setText("");
        txtDesc.setText("");
        txtSalarioMinimo.setValue(0);
        txtSalarioMaximo.setValue(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Comboitem> cmbDepartamento;
    private javax.swing.JComboBox<Comboitem> cmbRiesgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPuestos;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JSpinner txtSalarioMaximo;
    private javax.swing.JSpinner txtSalarioMinimo;
    // End of variables declaration//GEN-END:variables
}
