/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.nuevoCandidato;

import com.github.lgooddatepicker.zinternaltools.Convert;
import com.mysql.cj.protocol.Message;
import common.DateLabelFormatter;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JOptionPane;
import model.ExperienciaLaboral;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Joel Grullon
 */
public class AgregarCapacitacionForm extends javax.swing.JInternalFrame {
    
    private NuevoCandidatoForm nuevoCandidatoForm;
    private JDatePickerImpl datePickerDesde;
    private JDatePickerImpl datePickerHasta;

    /**
     * Creates new form AgregarExperienciaForm
     */
    public AgregarCapacitacionForm(NuevoCandidatoForm baseForm) {
        nuevoCandidatoForm=baseForm;
        initComponents();
        
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");
        
        UtilDateModel modelFechaDesde = new UtilDateModel();
        modelFechaDesde.setSelected(true); // o setDate(año, mes, día)

        JDatePanelImpl datePanelDesde = new JDatePanelImpl(modelFechaDesde, p);
        datePickerDesde = new JDatePickerImpl(datePanelDesde, new DateLabelFormatter());
        panelFechaDesde.setLayout(new java.awt.FlowLayout());
        panelFechaDesde.add(datePickerDesde);
        
        UtilDateModel modelFechaHasta = new UtilDateModel();
        modelFechaHasta.setSelected(true); // o setDate(año, mes, día)
        
        JDatePanelImpl datePanelHasta = new JDatePanelImpl(modelFechaHasta, p);
        datePickerHasta = new JDatePickerImpl(datePanelHasta, new DateLabelFormatter());
        panelFechaHasta.setLayout(new java.awt.FlowLayout());
        panelFechaHasta.add(datePickerHasta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCapacitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelFechaHasta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtInstitucion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelFechaDesde = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbNivel = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Agregar Capacitacion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNombreCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 500, -1));

        jLabel2.setText("Nivel:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, -1, -1));

        jLabel3.setText("Descripcion de la carrera:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(panelFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel4.setText("Hasta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        getContentPane().add(txtInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 500, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 630, -1));

        jLabel5.setText("Carrera o Capacitacion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel6.setText("Institucion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));
        getContentPane().add(panelFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 100, -1, -1));

        jLabel7.setText("Desde:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 10, -1));

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnico", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 500, -1));

        jCheckBox1.setText("Aun cursando");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        // if(txtNombreCapacitacion.getText()==null|| txtNombreCapacitacion.getText().isBlank()){
        //     JOptionPane.showMessageDialog(this, "El campo de Empresa es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
        //     return;
        // }
        
        // if(txtInstitucion.getText()==null|| txtInstitucion.getText().isBlank()){
        //     JOptionPane.showMessageDialog(this, "El campo de Empresa es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
        //     return;
        // }
        
        // ExperienciaLaboral expLaboral=new ExperienciaLaboral();
        // expLaboral.setEmpresa(txtNombreCapacitacion.getText().trim());
        // expLaboral.setPuesto(txtInstitucion.getText().trim());
        // if(txtSalario.getValue()!=null)
        //     expLaboral.setSalario(new BigDecimal(txtSalario.getValue().toString()));
        
        // expLaboral.setDescripcion(txtDesc.getText());
        // expLaboral.setFechaDesde((LocalDate)datePickerDesde.getModel().getValue());
        // expLaboral.setFechaHasta((LocalDate)datePickerHasta.getModel().getValue());
        // nuevoCandidatoForm.agregarExperienciaLaboral(expLaboral);
        
        //this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFechaDesde;
    private javax.swing.JPanel panelFechaHasta;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombreCapacitacion;
    // End of variables declaration//GEN-END:variables
}
