/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.nuevoCandidato;

import com.github.lgooddatepicker.zinternaltools.Convert;
import com.mysql.cj.protocol.Message;
import common.DateLabelFormatter;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Properties;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import model.Competencia;
import model.ExperienciaLaboral;
import model.Idioma;
import model.IdiomaCandidato;
import model.NivelCapacitacion;
import model.NivelIdioma;
import service.IdiomaService;
import service.NivelIdiomaService;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Joel Grullon
 */
public class AgregarIdiomaCandidatoForm extends javax.swing.JInternalFrame {
    
    private NuevoCandidatoForm nuevoCandidatoForm;
    private JDatePickerImpl datePickerDesde;
    private JDatePickerImpl datePickerHasta;

    private IdiomaCandidato editingIdiomaCandidato;

    private IdiomaService idiomaService;
    private NivelIdiomaService nivelIdiomaService;

    /**
     * Creates new form AgregarExperienciaForm
     */
    public AgregarIdiomaCandidatoForm(NuevoCandidatoForm baseForm) {
        nuevoCandidatoForm=baseForm;
        idiomaService=new IdiomaService();
        nivelIdiomaService=new NivelIdiomaService();
            
        initComponents();

        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
    }

    public AgregarIdiomaCandidatoForm(NuevoCandidatoForm baseForm, IdiomaCandidato idiomaCandidato) {
        nuevoCandidatoForm=baseForm;
        idiomaService=new IdiomaService();
        nivelIdiomaService=new NivelIdiomaService();

        initComponents();

        setTitle("Editar Idioma");

        editingIdiomaCandidato=idiomaCandidato;

        Idioma idiomaCargado=idiomaService.findById(idiomaCandidato.getIdiomaId());
        cmbIdioma.setSelectedItem(idiomaCargado);

        NivelIdioma nivelCargado=nivelIdiomaService.findById(idiomaCandidato.getNivelId());
        cmbNivel.setSelectedItem(nivelCargado);

        setTitle("Editar Idioma");
        btnAgregar.setText("Editar");
        btnAgregar.addActionListener(this::btnEditarActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        cmbNivel = new javax.swing.JComboBox<>();
        cmbIdioma = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Agregar Idioma");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nivel:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        jLabel5.setText("Idioma:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 10, -1));

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        DefaultComboBoxModel<Idioma> modeloIdioma = new DefaultComboBoxModel<>();

        for (Idioma i : idiomaService.getAll()) {
            modeloIdioma.addElement(i);
        }

        cmbIdioma.setModel(modeloIdioma);
        getContentPane().add(cmbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, -1));

        DefaultComboBoxModel<NivelIdioma> modeloNivel = new DefaultComboBoxModel<>();

        for (NivelIdioma ni : nivelIdiomaService.getAll()) {
            modeloNivel.addElement(ni);
        }

        cmbNivel.setModel(modeloNivel);
        getContentPane().add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {       
        IdiomaCandidato idiomaCandidato=new IdiomaCandidato();

        Idioma idiomaSeleccionado=(Idioma)cmbIdioma.getSelectedItem();
        idiomaCandidato.setIdiomaId(idiomaSeleccionado.getIdIdioma());
        idiomaCandidato.setIdioma(idiomaSeleccionado);
        
        NivelIdioma nivelSeleccionado=(NivelIdioma)cmbNivel.getSelectedItem();
        idiomaCandidato.setNivelId(nivelSeleccionado.getIdNivel());
        idiomaCandidato.setNivelIdioma(nivelSeleccionado);

        nuevoCandidatoForm.agregarIdioma(idiomaCandidato);

        this.dispose();
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {

        Idioma idiomaSeleccionado=(Idioma)cmbIdioma.getSelectedItem();
        editingIdiomaCandidato.setIdiomaId(idiomaSeleccionado.getIdIdioma());
        editingIdiomaCandidato.setIdioma(idiomaSeleccionado);
        
        NivelIdioma nivelSeleccionado=(NivelIdioma)cmbNivel.getSelectedItem();
        editingIdiomaCandidato.setNivelId(nivelSeleccionado.getIdNivel());
        editingIdiomaCandidato.setNivelIdioma(nivelSeleccionado);

        nuevoCandidatoForm.recargarIdiomas();

        this.dispose();
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<Idioma> cmbIdioma;
    private javax.swing.JComboBox<NivelIdioma> cmbNivel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
