/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.nuevoCandidato;

import com.github.lgooddatepicker.zinternaltools.Convert;
import com.mysql.cj.protocol.Message;
import common.DateLabelFormatter;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JOptionPane;

import model.Competencia;
import model.ExperienciaLaboral;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Joel Grullon
 */
public class AgregarCompetenciaForm extends javax.swing.JInternalFrame {
    
    private NuevoCandidatoForm nuevoCandidatoForm;
    private JDatePickerImpl datePickerDesde;
    private JDatePickerImpl datePickerHasta;

    private Competencia editCompetencia;

    /**
     * Creates new form AgregarExperienciaForm
     */
    public AgregarCompetenciaForm(NuevoCandidatoForm baseForm) {
        nuevoCandidatoForm=baseForm;
        initComponents();
    }

    public AgregarCompetenciaForm(NuevoCandidatoForm baseForm, Competencia comp) {
        nuevoCandidatoForm=baseForm;
        initComponents();

        editCompetencia=comp;

        txtCompetencia.setText(comp.getNombreCompetencia());
        txtDesc.setText(comp.getDescripcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCompetencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar Competencia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCompetencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, -1));

        jLabel3.setText("Descripcion de la competencia:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 400, -1));

        jLabel5.setText("Competencia:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 10, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        // if(txtCompetencia.getText()==null|| txtCompetencia.getText().isBlank()){
        //     JOptionPane.showMessageDialog(this, "El campo de Competencia es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
        //     return;
        // }
        
        // if(txtPuesto.getText()==null|| txtPuesto.getText().isBlank()){
        //     JOptionPane.showMessageDialog(this, "El campo de Empresa es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
        //     return;
        // }
        
        // ExperienciaLaboral expLaboral=new ExperienciaLaboral();
        // expLaboral.setEmpresa(txtCompetencia.getText().trim());
        // expLaboral.setPuesto(txtPuesto.getText().trim());
        // if(txtSalario.getValue()!=null)
        //     expLaboral.setSalario(new BigDecimal(txtSalario.getValue().toString()));
        
        // expLaboral.setDescripcion(txtDesc.getText());
        // expLaboral.setFechaDesde((LocalDate)datePickerDesde.getModel().getValue());
        // expLaboral.setFechaHasta((LocalDate)datePickerHasta.getModel().getValue());
        // nuevoCandidatoForm.agregarExperienciaLaboral(expLaboral);
        
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCompetencia;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables
}
