/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.nuevoCandidato;

import com.github.lgooddatepicker.zinternaltools.Convert;
import com.mysql.cj.protocol.Message;
import common.DateLabelFormatter;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import model.ExperienciaLaboral;
import model.Recomendacion;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author Joel Grullon
 */
public class AgregarRecomendacionForm extends javax.swing.JInternalFrame {
    
    private NuevoCandidatoForm nuevoCandidatoForm;
    private JDatePickerImpl datePickerDesde;
    private JDatePickerImpl datePickerHasta;

    /**
     * Creates new form AgregarExperienciaForm
     */
    public AgregarRecomendacionForm(NuevoCandidatoForm baseForm) {
        nuevoCandidatoForm=baseForm;
        initComponents();
    }

    public AgregarRecomendacionForm(NuevoCandidatoForm baseForm, Recomendacion reco) {
        nuevoCandidatoForm=baseForm;
        initComponents();
        setTitle("Editar Recomendacion");

        txtNombre.setText(reco.getNombreRecomendador());
        txtEmpresa.setText(reco.getEmpresa());
        txtPuesto.setText(reco.getPuesto());
        txtContacto.setText(reco.getContacto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtEmpresa = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Agregar Recomendacion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, -1));

        jLabel2.setText("Contacto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));
        getContentPane().add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 360, -1));

        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel6.setText("Empresa:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 360, -1));
        getContentPane().add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 360, -1));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 10, -1));

        jLabel4.setText("Puesto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        if(txtNombre.getText()==null|| txtNombre.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El campo de Nombre es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(txtEmpresa.getText()==null || txtEmpresa.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El campo de Empresa es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(txtPuesto.getText()==null || txtPuesto.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El campo de Puesto es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(txtContacto.getText()==null || txtContacto.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El campo de Empresa es requerido", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Recomendacion recomendacion=new Recomendacion();
        recomendacion.setNombreRecomendador(txtNombre.getText().trim());
        recomendacion.setEmpresa(txtEmpresa.getText().trim());
        recomendacion.setPuesto(txtPuesto.getText().trim());
        recomendacion.setContacto(txtContacto.getText().trim());

        nuevoCandidatoForm.agregarRecomendacion(recomendacion);
        nuevoCandidatoForm.recargarRecomendaciones();

        this.dispose();
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
