package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import model.Idioma;
import service.IdiomaService;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;






/**
 *
 * @author LENOVO
 */
public class IdiomaForm extends javax.swing.JFrame {
   private DefaultTableModel tblModel;
    private int filaSeleccionada = -1;
    private final IdiomaService idiomaService;


    private void initTable() {
    String[] header = {"ID","Idioma", "Nivel"};
    tblModel = new DefaultTableModel(header, 0);
    FrmTable.setModel(tblModel);
    
      
      
    
}
    public IdiomaForm() throws SQLException {
    this.idiomaService = new IdiomaService();
    initComponents();
    initTable();
    cargarIdiomasEnTabla();
}

// Al final de initTable(), para cargar datos al iniciar:
private void cargarIdiomasEnTabla() {
    tblModel.setRowCount(0);
    List<Idioma> lista = idiomaService.getAll();
    for (Idioma idi : lista) {
        String nivel = "";  // si recién cargaste, nivel vacío
        tblModel.addRow(new Object[]{ idi.getIdIdioma(), idi.getNombreIdioma(), nivel });
    }
}
private void limpiarCampos() {
    jTextField1.setText(""); 
    jComboBox1.setSelectedIndex(0); 
    FrmTable.clearSelection(); 
}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Addbtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Idiomalabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Nivellabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FrmTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        Addbtn.setBackground(new java.awt.Color(153, 255, 153));
        Addbtn.setText("Agregar");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Addbtn);

        Editbtn.setBackground(new java.awt.Color(204, 255, 255));
        Editbtn.setText("Editar");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Editbtn);

        deletebtn.setBackground(new java.awt.Color(255, 102, 102));
        deletebtn.setText("Eliminar");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar idiomas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        Idiomalabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        Idiomalabel.setText("Idioma:");
        jPanel5.add(Idiomalabel, new java.awt.GridBagConstraints());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        jPanel5.add(jTextField1, gridBagConstraints);

        Nivellabel.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        Nivellabel.setText("Nivel:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel5.add(Nivellabel, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Básico avanzado", "Intermedio bajo", "Intermedio avanzado", "Intermedio", "Avanzado bajo", "Avanzado ", "Nativo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        jPanel5.add(jComboBox1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setText("Gestión de Idiomas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Idiomas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        FrmTable.setBackground(new java.awt.Color(204, 255, 255));
        FrmTable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        FrmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Idioma", "Nivel"
            }
        ));
        FrmTable.setFocusable(false);
        jScrollPane1.setViewportView(FrmTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 407;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 26, 11, 11);
        jPanel4.add(jScrollPane1, gridBagConstraints);
        jPanel4.add(jTabbedPane1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
         int fila = FrmTable.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para editar.");
        return;
    }

    int id = (int) tblModel.getValueAt(fila, 0);
    String nuevoNombre = jTextField1.getText().trim();
    String nuevoNivel = jComboBox1.getSelectedItem().toString();

    if (nuevoNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe escribir un idioma.");
        return;
    }

    Idioma idioma = idiomaService.findById(id);
    idioma.setNombreIdioma(nuevoNombre);
    //idioma.setNivel(nuevoNivel);

    if (idiomaService.update(idioma)) {
        cargarIdiomasEnTabla();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar.");
    }
    }//GEN-LAST:event_EditbtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
      String nombre = jTextField1.getText().trim();
    String nivel = jComboBox1.getSelectedItem().toString();

    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe escribir un idioma.");
        return;
    }

    Idioma idioma = new Idioma();
    idioma.setNombreIdioma(nombre);
    //idioma.setNivel(nivel); 

    if (idiomaService.insert(idioma)) {
        cargarIdiomasEnTabla();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar en BD.");
        //<editor-fold defaultstate="collapsed" desc="comment">
    }
//</editor-fold>
 
    }//GEN-LAST:event_AddbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
    int fila = FrmTable.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
        return;
    }

    int id = (int) tblModel.getValueAt(fila, 0);
    Idioma idioma = idiomaService.findById(id);

    int conf = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este idioma?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (conf == JOptionPane.YES_OPTION) {
        if (idiomaService.delete(idioma)) {
            cargarIdiomasEnTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
    }
    }//GEN-LAST:event_deletebtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> {
        try {
            new IdiomaForm().setVisible(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error conectando a la base de datos: " + ex.getMessage());
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JTable FrmTable;
    private javax.swing.JLabel Idiomalabel;
    private javax.swing.JLabel Nivellabel;
    private javax.swing.JButton deletebtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
    
 


