/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

import common.WrapLayout;
import model.Puesto;
import service.PuestoService;

/**
 *
 * @author Joel Grullon
 */
public class ListadoPuestosForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoPuestosForm
     */
    public ListadoPuestosForm() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (Exception e) {
        }
        
        cargarPuestos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        cardsPanel = new javax.swing.JPanel();

        setBorder(null);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        cardsPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardsPanelFocusGained(evt);
            }
        });
        cardsPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 10, 10));
        scrollPane.setViewportView(cardsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.toBack();
    }//GEN-LAST:event_formFocusGained

    private void cardsPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardsPanelFocusGained
        this.toBack();
    }//GEN-LAST:event_cardsPanelFocusGained

    private void cargarPuestos() {
        // Aquí debes reemplazar con tu acceso real a la BD
        PuestoService dao = new PuestoService(); // Asegúrate de tener esta clase
        List<Puesto> puestos = dao.getAll();

        cardsPanel.removeAll();

        for (Puesto p : puestos) {
            cardsPanel.add(crearCardPuesto(p));
            cardsPanel.add(Box.createRigidArea(new Dimension(0, 10))); // Espacio entre cards
        }

        cardsPanel.revalidate();
        cardsPanel.repaint();
    }

    private JPanel crearCardPuesto(Puesto puesto) {
        JPanel card = new JPanel();
card.setPreferredSize(new Dimension(200, 100)); // Tamaño del card
card.setBorder(BorderFactory.createLineBorder(Color.GRAY));
card.add(new JLabel("Puesto: " + puesto.getNombrePuesto()));
cardsPanel.add(card);
        card.setBackground(new Color(245, 245, 245)); // Gris claro

        JLabel lblNombre = new JLabel("Puesto: " + puesto.getNombrePuesto());
        JLabel lblDescripcion = new JLabel("Descripción: " + puesto.getDescripcion());
        JLabel lblSalario = new JLabel("Salario: " + puesto.getSalarioMinimo() + " - " + puesto.getSalarioMaximo());
        JLabel lblVacantes = new JLabel("Vacantes: " + puesto.getVacantes());

        lblNombre.setFont(new Font("Arial", Font.BOLD, 14));
        lblDescripcion.setFont(new Font("Arial", Font.PLAIN, 13));
        lblSalario.setFont(new Font("Arial", Font.PLAIN, 13));
        lblVacantes.setFont(new Font("Arial", Font.PLAIN, 13));

        card.add(lblNombre);
        card.add(lblDescripcion);
        card.add(lblSalario);
        card.add(lblVacantes);

        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

        return card;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
