/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package view;

import javax.swing.JLayeredPane;
import javax.swing.JMenuBar;
import javax.swing.SwingUtilities;

import common.Session;
import model.Puesto;
import model.Puesto;
import view.departamentoForm.DepartamentosForm;
import view.empleadoForm.EmpleadoForm;
import view.formularioPrincipal.ListadoPuestosForm;
import view.idiomaForm.IdiomaForm;
import view.nuevoCandidato.NuevoCandidatoForm;
import view.puestosForm.PuestosForm;

/**
 *
 * @author JoelGrullon
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        // LoginForm login=new LoginForm(this, true);
        // login.setVisible(true);
        initComponents();

        if (!Session.isAuthenticated()) {

            ListadoPuestosForm listado = new ListadoPuestosForm();
            listado.setBorder(null);

            mainDesktop.add(listado); // mainDesktop es tu JDesktopPane
            listado.setVisible(true);

            mainDesktop.setLayer(listado, JLayeredPane.FRAME_CONTENT_LAYER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktop = new javax.swing.JDesktopPane();
        ListadoPuestosForm = new javax.swing.JInternalFrame();
        scrollCards = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuEmpresa = new javax.swing.JMenu();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuDepartamentos = new javax.swing.JMenuItem();
        mnuIdioma = new javax.swing.JMenuItem();
        mnuVacantes = new javax.swing.JMenu();
        mnuPuestos = new javax.swing.JMenuItem();
        mnuCandidatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListadoPuestosForm.setClosable(true);
        ListadoPuestosForm.setIconifiable(true);
        ListadoPuestosForm.setMaximizable(true);
        ListadoPuestosForm.setResizable(true);
        ListadoPuestosForm.setTitle("Listado de Puestos");
        ListadoPuestosForm.getContentPane().add(scrollCards, java.awt.BorderLayout.CENTER);

        jButton1.setText("jButton1");

        mnuEmpresa.setMnemonic('f');
        mnuEmpresa.setText("Empresa");

        mnuEmpleados.setMnemonic('o');
        mnuEmpleados.setText("Gestionar Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        mnuEmpresa.add(mnuEmpleados);

        mnuDepartamentos.setMnemonic('s');
        mnuDepartamentos.setText("Gestionar Departamentos");
        mnuDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDepartamentosActionPerformed(evt);
            }
        });
        mnuEmpresa.add(mnuDepartamentos);

        mnuIdioma.setMnemonic('a');
        mnuIdioma.setText("Gestionar Idiomas");
        mnuIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIdiomaActionPerformed(evt);
            }
        });
        mnuEmpresa.add(mnuIdioma);

        menuBar.add(mnuEmpresa);

        mnuVacantes.setMnemonic('e');
        mnuVacantes.setText("Vacantes");

        mnuPuestos.setMnemonic('t');
        mnuPuestos.setText("Gestionar Puestos");
        mnuPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPuestosActionPerformed(evt);
            }
        });
        mnuVacantes.add(mnuPuestos);

        mnuCandidatos.setMnemonic('y');
        mnuCandidatos.setText("Gestionar Candidatos");
        mnuCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCandidatosActionPerformed(evt);
            }
        });
        mnuVacantes.add(mnuCandidatos);

        menuBar.add(mnuVacantes);

        if (Session.isAuthenticated()) {
            setJMenuBar(menuBar);
        } else {
            setJMenuBar(new JMenuBar());
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1469, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuEmpleadosActionPerformed
        EmpleadoForm empForm = new EmpleadoForm(mainDesktop);
        mainDesktop.add(empForm);
        empForm.setVisible(true);

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }// GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnuDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuDepartamentosActionPerformed
        DepartamentosForm dedForm = new DepartamentosForm();
        mainDesktop.add(dedForm);
        dedForm.setVisible(true);

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }// GEN-LAST:event_mnuDepartamentosActionPerformed

    private void mnuIdiomaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuIdiomaActionPerformed
        IdiomaForm idiomaForm = new IdiomaForm();
        mainDesktop.add(idiomaForm);
        idiomaForm.setVisible(true);

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }// GEN-LAST:event_mnuIdiomaActionPerformed

    private void mnuPuestosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuPuestosActionPerformed
        PuestosForm pForm = new PuestosForm(mainDesktop);
        mainDesktop.add(pForm);
        pForm.setVisible(true);

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }// GEN-LAST:event_mnuPuestosActionPerformed

    private void mnuCandidatosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnuCandidatosActionPerformed
        CandidatosForm cForm = new CandidatosForm(mainDesktop);
        mainDesktop.add(cForm);
        cForm.setVisible(true);

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }// GEN-LAST:event_mnuCandidatosActionPerformed

    private void mostrarListadoPuestos() {
        ListadoPuestosForm listado = new ListadoPuestosForm();
        mainDesktop.add(listado);
        listado.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ListadoPuestosForm;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCandidatos;
    private javax.swing.JMenuItem mnuDepartamentos;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenu mnuEmpresa;
    private javax.swing.JMenuItem mnuIdioma;
    private javax.swing.JMenuItem mnuPuestos;
    private javax.swing.JMenu mnuVacantes;
    private javax.swing.JScrollPane scrollCards;
    // End of variables declaration//GEN-END:variables

}
