/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author Joel Grullon
 */
public class NuevoCandidatoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoCandidatoForm
     */
    public NuevoCandidatoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExp = new javax.swing.JTable();
        btnAgregarExp = new javax.swing.JButton();
        btnEditarExp = new javax.swing.JButton();
        btnEliminarExp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCap = new javax.swing.JTable();
        btnAgregarCap = new javax.swing.JButton();
        btnEditarCap = new javax.swing.JButton();
        btnEliminarCap = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblExp1 = new javax.swing.JTable();
        btnAgregarExp1 = new javax.swing.JButton();
        btnEditarExp1 = new javax.swing.JButton();
        btnEliminarExp1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblExp2 = new javax.swing.JTable();
        btnAgregarExp2 = new javax.swing.JButton();
        btnEditarExp2 = new javax.swing.JButton();
        btnEliminarExp2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblExp3 = new javax.swing.JTable();
        btnAgregarIdioma = new javax.swing.JButton();
        btnEditarIdioma = new javax.swing.JButton();
        btnEliminarIdioma = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JFormattedTextField();
        cmbPuesto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnVerPuestos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarExp3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Candidato");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Candidato");

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Experiencia Laboral"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre Empresa"
            }
        ));
        jScrollPane1.setViewportView(tblExp);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 680, 180));

        btnAgregarExp.setText("Agregar");
        jPanel2.add(btnAgregarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btnEditarExp.setText("Editar");
        jPanel2.add(btnEditarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        btnEliminarExp.setText("Eliminar");
        jPanel2.add(btnEliminarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 700, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Capacitaciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Carrera", "Institucion"
            }
        ));
        jScrollPane2.setViewportView(tblCap);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 328, 184));

        btnAgregarCap.setText("Agregar");
        jPanel3.add(btnAgregarCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btnEditarCap.setText("Editar");
        jPanel3.add(btnEditarCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        btnEliminarCap.setText("Eliminar");
        jPanel3.add(btnEliminarCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 350, 250));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Competencias"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Competencia"
            }
        ));
        jScrollPane3.setViewportView(tblExp1);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 328, 184));

        btnAgregarExp1.setText("Agregar");
        jPanel4.add(btnAgregarExp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btnEditarExp1.setText("Editar");
        jPanel4.add(btnEditarExp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        btnEliminarExp1.setText("Eliminar");
        jPanel4.add(btnEliminarExp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 350, 250));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Recomendaciones"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExp2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Puesto"
            }
        ));
        jScrollPane4.setViewportView(tblExp2);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 328, 184));

        btnAgregarExp2.setText("Agregar");
        jPanel5.add(btnAgregarExp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btnEditarExp2.setText("Editar");
        jPanel5.add(btnEditarExp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        btnEliminarExp2.setText("Eliminar");
        jPanel5.add(btnEliminarExp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 350, 250));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Idiomas"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExp3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Puesto"
            }
        ));
        jScrollPane6.setViewportView(tblExp3);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 328, 184));

        btnAgregarIdioma.setText("Agregar");
        jPanel7.add(btnAgregarIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btnEditarIdioma.setText("Editar");
        jPanel7.add(btnEditarIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 24, -1, -1));

        btnEliminarIdioma.setText("Eliminar");
        jPanel7.add(btnEliminarIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 24, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, 350, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos basicos"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 620, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 620, -1));

        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, -1));

        jLabel4.setText("Cedula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 86, -1, -1));

        txtCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 620, -1));

        cmbPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 530, -1));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, -1, -1));

        btnVerPuestos.setText("Mas Info.");
        jPanel1.add(btnVerPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel6.setText("Salario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 176, -1, -1));

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 620, -1));

        txtEmail.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 620, -1));

        jLabel7.setText("Puesto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, -1, -1));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 210));

        btnAgregarExp3.setText("Enviar Solicitud");
        jPanel6.add(btnAgregarExp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 970, -1, -1));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1000, 70, 20));

        jScrollPane5.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCap;
    private javax.swing.JButton btnAgregarExp;
    private javax.swing.JButton btnAgregarExp1;
    private javax.swing.JButton btnAgregarExp2;
    private javax.swing.JButton btnAgregarExp3;
    private javax.swing.JButton btnAgregarIdioma;
    private javax.swing.JButton btnEditarCap;
    private javax.swing.JButton btnEditarExp;
    private javax.swing.JButton btnEditarExp1;
    private javax.swing.JButton btnEditarExp2;
    private javax.swing.JButton btnEditarIdioma;
    private javax.swing.JButton btnEliminarCap;
    private javax.swing.JButton btnEliminarExp;
    private javax.swing.JButton btnEliminarExp1;
    private javax.swing.JButton btnEliminarExp2;
    private javax.swing.JButton btnEliminarIdioma;
    private javax.swing.JButton btnVerPuestos;
    private javax.swing.JComboBox<String> cmbPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblCap;
    private javax.swing.JTable tblExp;
    private javax.swing.JTable tblExp1;
    private javax.swing.JTable tblExp2;
    private javax.swing.JTable tblExp3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
