/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.empleadoForm;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Properties;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

import common.Comboitem;
import common.DateLabelFormatter;
import model.Empleado;
import model.Puesto;
import service.EmpleadoService;
import service.PuestoService;

/**
 *
 * @author Joel Grullon
 */
public class EditarEmpleadoForm extends javax.swing.JInternalFrame {

    private EmpleadoService empleadoService;
    private PuestoService puestoService;
    private Empleado empleadoEditado;
    private EmpleadoForm parent;

    private List<Puesto> listaPuestos;

    private JDatePickerImpl datePickerFechaIngreso;


    /**
     * Creates new form EditarEmpleadoForm
     */
    public EditarEmpleadoForm(Empleado empleado, EmpleadoForm empForm) {
        empleadoEditado=empleado;
        parent=empForm;

        empleadoService=new EmpleadoService();
        puestoService=new PuestoService();

        initComponents();
        setupPanelFechaIngreso();
        cargarPuestos();

        cargarEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelFechaIngreso = new javax.swing.JPanel();
        cmbPuesto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);

        setTitle("Editar Empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fecha Ingreso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 480, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 480, -1));

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel4.setText("Puesto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));
        getContentPane().add(panelFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        getContentPane().add(cmbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 270, -1));

        jLabel5.setText("Cedula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        txtEditar.setText("Editar");
        txtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarActionPerformed(evt);
            }
        });
        getContentPane().add(txtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupPanelFechaIngreso(){
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");

        UtilDateModel modelFechaIngreso = new UtilDateModel();
        modelFechaIngreso.setSelected(true); // o setDate(año, mes, día)

        JDatePanelImpl datePanelFechaIngreso = new JDatePanelImpl(modelFechaIngreso, p);
        datePickerFechaIngreso = new JDatePickerImpl(datePanelFechaIngreso, new DateLabelFormatter());
        panelFechaIngreso.setLayout(new java.awt.FlowLayout());
        panelFechaIngreso.add(datePickerFechaIngreso);
    }

    private void cargarPuestos(){
        cmbPuesto.removeAllItems();

        listaPuestos=puestoService.getAll();

        for (Puesto p : listaPuestos) {
            cmbPuesto.addItem(new Comboitem(p.getIdPuesto(), p.getNombrePuesto()));
        }
    }

    private void cargarEmpleado(){
        txtNombre.setText(empleadoEditado.getNombreEmpleado());
        txtApellido.setText(empleadoEditado.getApellidoEmpleado());
        txtCedula.setText(empleadoEditado.getCedula());

        Puesto puestoSeleccionado=listaPuestos.stream()
        .filter(x->x.getIdPuesto()==empleadoEditado.getPuestoId())
        .findFirst()
        .orElse(null);

        cmbPuesto.setSelectedItem(new Comboitem(puestoSeleccionado.getIdPuesto(), puestoSeleccionado.getNombrePuesto()));

        UtilDateModel modelFechaIngreso = (UtilDateModel) datePickerFechaIngreso.getModel();
        LocalDate fechaIngreso = empleadoEditado.getFechaIngreso();
        modelFechaIngreso.setDate(fechaIngreso.getYear(), fechaIngreso.getMonthValue() - 1, fechaIngreso.getDayOfMonth());
    }

    private void txtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarActionPerformed
        empleadoEditado.setCedula(txtCedula.getText());
        empleadoEditado.setNombreEmpleado(txtNombre.getText());
        empleadoEditado.setApellidoEmpleado(txtApellido.getText());

        empleadoEditado.setPuestoId(((Comboitem)cmbPuesto.getSelectedItem()).getId());

        UtilDateModel fechaIngresoModel = (UtilDateModel) datePickerFechaIngreso.getModel();
        empleadoEditado.setFechaIngreso(fechaIngresoModel.getValue().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        
        if(!empleadoService.update(empleadoEditado)){
            JOptionPane.showMessageDialog(this, "Error al editar el empleado");
            return;
        }

        JOptionPane.showMessageDialog(this, "Empleado editado correctamente");
        parent.cargarEmpleados();
        this.dispose();

        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
    }//GEN-LAST:event_txtEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Comboitem> cmbPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelFechaIngreso;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JButton txtEditar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
