/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.formularioPrincipal;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

import model.Departamento;
import model.Puesto;
import model.RiesgoPuesto;
import service.DepartamentoService;
import service.RiesgoPuestoService;

/**
 *
 * @author Joel Grullon
 */
public class DetallesPuestoForm extends javax.swing.JInternalFrame {

    private Puesto puesto;
    private DepartamentoService departamentoService;
    private RiesgoPuestoService riesgoService;

    /**
     * Creates new form DetallesPuestoForm
     */
    public DetallesPuestoForm(Puesto puesto) {

        departamentoService=new DepartamentoService();
        riesgoService=new RiesgoPuestoService();

        this.puesto=puesto;
        cargarRelacionesPuesto();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setClosable(true);
        // setResizable(true);

        setTitle("Detalle del Puesto");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        // Nombre del puesto
        JLabel lblNombre = new JLabel("Puesto: " + puesto.getNombrePuesto());
        lblNombre.setFont(lblNombre.getFont().deriveFont(Font.BOLD, 16f));
        lblNombre.setSize(750, HEIGHT);
        mainPanel.add(lblNombre);
        mainPanel.add(Box.createVerticalStrut(10));

        // Departamento
        JLabel lblDepto = new JLabel("Departamento: " +
                (puesto.getDepartamento() != null ? puesto.getDepartamento().getNombreDepartamento() : "N/A"));
        mainPanel.add(lblDepto);

        // Riesgo
        JLabel lblRiesgo = new JLabel("Riesgo: " +
                (puesto.getRiesgo() != null ? puesto.getRiesgo().getNombreRiesgo() : "N/A"));
        mainPanel.add(lblRiesgo);

        // Salario
        JLabel lblSalario = new JLabel(String.format("Salario: $%,.2f - $%,.2f",
                puesto.getSalarioMinimo(), puesto.getSalarioMaximo()));
        mainPanel.add(lblSalario);

        // Vacantes
        JLabel lblVacantes = new JLabel("Vacantes: " + puesto.getVacantes());
        mainPanel.add(lblVacantes);
        mainPanel.add(Box.createVerticalStrut(10));

        // Descripción (ajustable)
        JTextArea txtDescripcion = new JTextArea(puesto.getDescripcion());
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(mainPanel.getBackground());
        txtDescripcion.setBorder(BorderFactory.createTitledBorder("Descripción"));
        mainPanel.add(txtDescripcion);

        mainPanel.add(Box.createVerticalStrut(15));

        // 

        // Scroll por si la descripción es muy larga
        JScrollPane scrollPane = new JScrollPane(mainPanel);
        scrollPane.setBorder(null);
        add(scrollPane);

        //setLocationRelativeTo(null);

        pack();

        setSize(800, 600);
    }

    private void cargarRelacionesPuesto(){
        Departamento depa=departamentoService.findById(puesto.getDepartamentoId());
        puesto.setDepartamento(depa);

        RiesgoPuesto riesgo=riesgoService.findById(puesto.getRiesgoId());
        puesto.setRiesgo(riesgo);
    }

    @Override
    public void dispose() {
        SwingUtilities.invokeLater(() -> {
            getParent().revalidate();
            getParent().repaint();
        });
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
